module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",

    // Staff
    FORM_STAFF_USER: "FORM_STAFF_USER",
    FORM_STAFF_ROLE: "FORM_STAFF_ROLE",

    // Product & Services
    FORM_IMPORT_PRODUCT: "FORM_IMPORT_PRODUCT",
    FORM_CREATE_PRODUCT: "FORM_CREATE_PRODUCT",

    // Product Stock
    FORM_EDIT_PRODUCT_STOCK: "FORM_EDIT_PRODUCT_STOCK",

    // Constant
    FORM_CREATE_CONSTANT_TAXES: "FORM_CREATE_CONSTANT_TAXES",
    FORM_CREATE_CONSTANT_CATEGORY: "FORM_CREATE_CONSTANT_CATEGORY",
    FORM_CREATE_CONSTANT_UNIT: "FORM_CREATE_CONSTANT_UNIT",
    FORM_CREATE_CONSTANT_CUSTOM_FIELD: "FORM_CREATE_CONSTANT_CUSTOM_FIELD",
    FORM_CREATE_CONSTANT_CONTRACT_TYPE: "FORM_CREATE_CONSTANT_CONTRACT_TYPE",

    // SUPERADMIN
    // COMPANY
    SUPERADMIN_FORM_CREATE_COMPANY: "SUPERADMIN_FORM_CREATE_COMPANY",
    SUPERADMIN_FORM_RESET_PASSWORD_COMPANY: "SUPERADMIN_FORM_RESET_PASSWORD_COMPANY",
    SUPERADMIN_FORM_UPGRADE_PLAN_COMPANY: "SUPERADMIN_FORM_UPGRADE_PLAN_COMPANY",
    SUPERADMIN_FORM_ADMIN_HUB_COMPANY: "SUPERADMIN_FORM_ADMIN_HUB_COMPANY",

    // PLAN
    SUPERADMIN_FORM_CREATE_PLAN: "SUPERADMIN_FORM_CREATE_PLAN",

    // COUPON
    SUPERADMIN_FORM_CREATE_COUPON: "SUPERADMIN_FORM_CREATE_COUPON",

    // ORDER
    SUPERADMIN_ORDER_DETAIL: "SUPERADMIN_ORDER_DETAIL",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
  },
});
