module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",

    // Staff
    FORM_STAFF_USER: "FORM_STAFF_USER",
    FORM_STAFF_ROLE: "FORM_STAFF_ROLE",

    // Product & Services
    FORM_IMPORT_PRODUCT: "FORM_IMPORT_PRODUCT",
    FORM_CREATE_PRODUCT: "FORM_CREATE_PRODUCT",

    // Product Stock
    FORM_EDIT_PRODUCT_STOCK: "FORM_EDIT_PRODUCT_STOCK",

    // Customer
    FORM_IMPORT_CUSTOMER: "FORM_IMPORT_CUSTOMER",
    FORM_CREATE_CUSTOMER: "FORM_CREATE_CUSTOMER",

    // Vendor
    FORM_IMPORT_VENDOR: "FORM_IMPORT_VENDOR",
    FORM_CREATE_VENDOR: "FORM_CREATE_VENDOR",

    // Banking Account
    FORM_CREATE_BANKING_ACCOUNT: "FORM_CREATE_BANKING_ACCOUNT",

    // Banking Transfer
    FORM_CREATE_BANKING_TRANSFER: "FORM_CREATE_BANKING_TRANSFER",

    // Invoice
    FORM_CREATE_CREDIT_NOTE_INVOICE: "FORM_CREATE_CREDIT_NOTE_INVOICE",

    // Revenue
    FORM_CREATE_REVENUE: "FORM_CREATE_REVENUE",

    // Credit Note
    FORM_CREATE_CREDIT_NOTE: "FORM_CREATE_CREDIT_NOTE",

    // Bill
    FORM_CREATE_DEBIT_NOTE_BILL: "FORM_CREATE_DEBIT_NOTE_BILL",

    // Payment
    FORM_CREATE_PAYMENT: "FORM_CREATE_PAYMENT",

    // Debit Note
    FORM_CREATE_DEBIT_NOTE: "FORM_CREATE_DEBIT_NOTE",

    // Chart Of Account
    FORM_CREATE_CHART_OF_ACCOUNT: "FORM_CREATE_CHART_OF_ACCOUNT",

    // Goal
    FORM_CREATE_GOAL: "FORM_CREATE_GOAL",
    // Asset
    FORM_CREATE_ASSET: "FORM_CREATE_ASSET",

    // Constant
    FORM_CREATE_CONSTANT_TAXES: "FORM_CREATE_CONSTANT_TAXES",
    FORM_CREATE_CONSTANT_CATEGORY: "FORM_CREATE_CONSTANT_CATEGORY",
    FORM_CREATE_CONSTANT_UNIT: "FORM_CREATE_CONSTANT_UNIT",
    FORM_CREATE_CONSTANT_CUSTOM_FIELD: "FORM_CREATE_CONSTANT_CUSTOM_FIELD",
    FORM_CREATE_CONSTANT_CONTRACT_TYPE: "FORM_CREATE_CONSTANT_CONTRACT_TYPE",

    // SUPERADMIN
    // COMPANY
    SUPERADMIN_FORM_CREATE_COMPANY: "SUPERADMIN_FORM_CREATE_COMPANY",
    SUPERADMIN_FORM_RESET_PASSWORD_COMPANY:
      "SUPERADMIN_FORM_RESET_PASSWORD_COMPANY",
    SUPERADMIN_FORM_UPGRADE_PLAN_COMPANY:
      "SUPERADMIN_FORM_UPGRADE_PLAN_COMPANY",
    SUPERADMIN_FORM_ADMIN_HUB_COMPANY: "SUPERADMIN_FORM_ADMIN_HUB_COMPANY",

    // PLAN
    SUPERADMIN_FORM_CREATE_PLAN: "SUPERADMIN_FORM_CREATE_PLAN",

    // COUPON
    SUPERADMIN_FORM_CREATE_COUPON: "SUPERADMIN_FORM_CREATE_COUPON",

    // ORDER
    SUPERADMIN_ORDER_DETAIL: "SUPERADMIN_ORDER_DETAIL",

    // LANDING PAGE
    // Menu Bar
    SUPERADMIN_FORM_CREATE_MENU_BAR: "SUPERADMIN_FORM_CREATE_MENU_BAR",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
  },
});
